// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiGUqZom_1WuG_c8UfnafBzikDkE0GwVA',
    appId: '1:438106723625:web:1f10b25714ae0b27755338',
    messagingSenderId: '438106723625',
    projectId: 'learnx-18db3',
    authDomain: 'learnx-18db3.firebaseapp.com',
    storageBucket: 'learnx-18db3.firebasestorage.app',
    measurementId: 'G-DYMWMP8GLB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5EeV6FUIDKvQLxX5M2jgsb-1Zto0484w',
    appId: '1:438106723625:android:cc2eb76c8a16e48a755338',
    messagingSenderId: '438106723625',
    projectId: 'learnx-18db3',
    storageBucket: 'learnx-18db3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYWxJk7Y91siytcmxjmtvoyy9G6xve1mY',
    appId: '1:438106723625:ios:2de63fe6a35d87ac755338',
    messagingSenderId: '438106723625',
    projectId: 'learnx-18db3',
    storageBucket: 'learnx-18db3.firebasestorage.app',
    iosBundleId: 'com.example.learnx',
  );
}
